apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        version: 8d99315-main
    spec:
      containers:
      - name: backend
        image: robrich/backend:8d99315-main
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: backend
        resources: {}
